// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace Utils {
	public static class UtilMethods {
		public static void Shuffle<T>(this IList<T> list)  
		{  
			System.Random rng = new System.Random();  
			int n = list.Count;  
			while (n > 1) {  
				n--;  
				int k = rng.Next(n + 1);  
				T value = list[k];  
				list[k] = list[n];  
				list[n] = value;  
			}
		}
		public static void SetImageAlpha(this Button button, float alpha) {
			Color c = button.image.color;
			if (c.a != alpha) {
				c.a = alpha;
				button.image.color = c;
			}
		}
	}
}
